config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "items#index"
  resources :items do
    get 'items/search'
    resources :orders, only: [:index, :create]
  end
  resources :users, only: [:show, :edit, :update]
  resources :admin, only: [:index, :show]
  resources :purchases, only: :show
  resources :comments, only: [:index, :new, :show, :create]
  resources :services do
  resources :service_orders, only: [:index, :new, :create]
  end
  resources :allappoints, only: [:index]
  resources :service_lists, only: [:index]
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :order
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    {id: 0, name: '--'}, 
    {id: 1, name: 'ユニフォーム'}, 
    {id: 2, name: 'トレーニングウェア'}, 
    {id: 3, name: 'プレーヤーグッズ'}, 
    {id: 4, name: 'タオル'}, 
    {id: 5, name: '応援グッズ'}, 
    {id: 6, name: 'アパレル'}, 
    {id: 7, name: 'ステーショナリー'}, 
    {id: 8, name: 'バッグ'}, 
    {id: 9, name: 'その他'}, 
]

  include ActiveHash::Associations
  has_many :items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user

  validates :message,     presence: true
end

app/models/delivery.rb
class Delivery < ActiveHash::Base
    self.data = [
      {id: 0, name: '--'}, 
      {id: 1, name: 'スタジアム受け取り可'}, 
      {id: 2, name: '宅配（着払い）のみ可'},
    ]
      include ActiveHash::Associations
      has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_one :order

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :delivery

  with_options presence: true do
    validates :image
    validates :name
    validates :info
    validates :price,    numericality: { with: /\A[0-9]+\z/, message: 'Half-width number' }
    validates :price_discrimination,    numericality: { with: /\A[0-9]+\z/, message: 'Half-width number' }
    end

  with_options numericality: { other_than: 0, message: 'Select'  } do
      validates :category_id 
      validates :delivery_id 
  end
end

app/models/member.rb
class Member < ActiveHash::Base
  self.data = [
    {id: 0, name: '--'}, 
    {id: 1, name: '年間チケット会員'}, 
    {id: 2, name: 'レギュラー会員'},
    {id: 3, name: '非会員'}
]
include ActiveHash::Associations
  has_many :users
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :item
  has_one    :address
end

app/models/order_donation.rb
class OrderDonation
  include ActiveModel::Model
  attr_accessor :user_id, :item_id, :postal_code, :prefecture_id, :city, :address, :building, :phone_number

  with_options presence: true do
    validates :postal_code, format: { with: /\A[0-9]{3}-[0-9]{4}\z/, message: "input correctly" }
    validates :city
    validates :address
    validates :user_id
    validates :item_id
    end
  
    validates :prefecture_id, numericality: { other_than: 0, message: "Select" }
    validates :phone_number,  presence: true, numericality: { with: /\A[0-9]+\z/, message: "is Half-width number" }
    validates :phone_number, format: { with: /\A[0-9]{,11}\z/, message: "is less than 11 number characters" }
  
    def save
      order = Order.create(user_id: user_id, item_id: item_id)
      Address.create(postal_code: postal_code, prefecture_id: prefecture_id, city: city, address: address, building: building, phone_number: phone_number, order_id: order.id)
    end
  end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    {id: 0, name: '--'}, {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, 
    {id: 3, name: '岩手県'}, {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, 
    {id: 6, name: '山形県'}, {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, 
    {id: 9, name: '栃木県'}, {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, 
    {id: 12, name: '千葉県'}, {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, 
    {id: 15, name: '新潟県'}, {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, 
    {id: 18, name: '福井県'}, {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, 
    {id: 21, name: '岐阜県'}, {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, 
    {id: 24, name: '三重県'}, {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, 
    {id: 27, name: '大阪府'}, {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, 
    {id: 30, name: '和歌山県'}, {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, 
    {id: 33, name: '岡山県'}, {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, 
    {id: 36, name: '徳島県'}, {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, 
    {id: 39, name: '高知県'}, {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, 
    {id: 42, name: '長崎県'}, {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, 
    {id: 45, name: '宮崎県'}, {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
]

  include ActiveHash::Associations
  has_many :items
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  has_many :service_orders

  validates :content,    presence: true
  validates :limit_day,  presence: true, format: { with: /\A\d{4}-\d{2}-\d{2}\z/, message: "input correctly" }
  validates :target,     presence: true
  validates :release_day,  presence: true, format: { with: /\A\d{4}-\d{2}-\d{2}\z/, message: "input correctly" }
end

app/models/service_order.rb
class ServiceOrder < ApplicationRecord
  belongs_to :user
  belongs_to :service
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :items
         has_many :orders
         has_many :comments
         has_many :services
         has_many :service_orders
         enum admin: {normal: 0, staff:1}

         extend ActiveHash::Associations::ActiveRecordExtensions
         belongs_to_active_hash :member

         validates :email,  presence: true
         validates :password,  presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message: 'Include both letters and numbers' }
         validates :name,  presence: true, format: { with: /\A[ぁ-んァ-ヶー-龥々]+\z/, message: 'Full-width characters' }
         validates :name_kana,  presence: true, format: { with: /\A[ァ-ヶー]+\z/, message: 'Full-width katakana characters' } 
         validates :member_id,  numericality: { other_than: 0, message: 'Select'  }
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def index
    @services = Service.all.order("created_at DESC")
    @services = Service.page(params[:page]).per(10).order("created_at DESC")
  end

  def new
     @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    if @service.save
      redirect_to  root_path
    else
      render :new
    end
  end

  def service_params
    params.require(:service).permit(:content, :limit_day, :target, :release_day).merge(user_id: current_user.id)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/allappoints_helper.rb
module AllappointsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/services/index.html.erb
<div class = "service-top">
  <h4 class = "service-all">サービス一覧</h4>
  <h4 class = "back-to-index"><%= link_to "戻る", user_path(current_user.id) %><h4>
</div>
<div class = "page">
  <%= paginate @services %>
</div>
<div class = "services-table">
<table class = "detail-table-general-service">
     <tbody>
        <tr>
          <th class="detail-service1">内容</th>
          <th class="detail-service2">締め切り</th>
          <th class="detail-service3">対象者</th>
          <th class="detail-service4">抽選発表日</th>
          <th class="detail-service5"></th>
        </tr>
        <% @services.each do |service| %>
        <tr>
          <td class="detail-service-value1"><%= service.content %></td>
          <td class="detail-service-value2"><%= service.limit_day %></td>
          <td class="detail-service-value3"><%= service.target %></td>
          <td class="detail-service-value4"><%= service.release_day %></td>
          <td class="detail-service-value5">
          <%=link_to '応募画面に進む', service_service_orders_path(service.id), class:"appoint" %>
          </td>
        </tr>
        <% end %>
      </tbody>
</table>
</div>

app/views/services/new.html.erb
<div class = "service-head">
  <h1 class = "service-title1">サービス投稿</h1>
  <h3 class = "back-to-shop"><%=link_to '戻る', root_path, class:"back-shop" %></h3>
</div>
<%= form_with model: @service, url: services_path, id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>

<%= render 'shared/error_messages', model: f.object %>

<div class="new-services1">
  <div class="services-explain">
     <div class="service-bold-text">
        ファンサービス内容
      <span class="indispensable">必須</span>
     </div>
    <%= f.text_area :content, class:"services-content", id:"service-name", placeholder:"例)サイン会", maxlength:"20" %>
  </div>
</div>
<div class = "new-services2">
      <div class="items-explain">
        <div class="weight-bold-text">
        対象者
        <span class="indispensable">必須</span>
       </div>
       <%= f.text_area :target, class:"services-target", id:"service-name", placeholder:"例)全員", maxlength:"20" %>
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
        申込期限
        <span class="indispensable">必須</span>
       </div>
      <%= f.text_area :limit_day, class:"services-limit", id:"service-name", placeholder:"例)2021-02-05", maxlength:"10" %>
     </div>
     <div class="items-explain">
        <div class="weight-bold-text">
        抽選発表日
        <span class="indispensable">必須</span>
       </div>
      <%= f.text_area :release_day, class:"services-release", id:"service-name", placeholder:"例)2021-02-05", maxlength:"10" %>
     </div>
</div>
<p></p>
<div class = "comment2">
  <%= f.submit "投稿する" ,class:"comment-btn1" %>
</div>
<% end %>