config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "items#index"
  resources :items do
    get 'items/search'
    resources :orders, only: [:index, :create]
  end
  resources :users, only: [:show, :edit, :update]
  resources :admin, only: [:index, :show]
  resources :purchases, only: :show
  resources :comments, only: [:index, :new, :show, :create]
  resources :services do
  resources :service_orders, only: [:index, :new, :create]
  end
  resources :allappoints, only: [:index]
  resources :service_lists, only: [:index]
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :order
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    {id: 0, name: '--'}, 
    {id: 1, name: 'ユニフォーム'}, 
    {id: 2, name: 'トレーニングウェア'}, 
    {id: 3, name: 'プレーヤーグッズ'}, 
    {id: 4, name: 'タオル'}, 
    {id: 5, name: '応援グッズ'}, 
    {id: 6, name: 'アパレル'}, 
    {id: 7, name: 'ステーショナリー'}, 
    {id: 8, name: 'バッグ'}, 
    {id: 9, name: 'その他'}, 
]

  include ActiveHash::Associations
  has_many :items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user

  validates :message,     presence: true
end

app/models/delivery.rb
class Delivery < ActiveHash::Base
    self.data = [
      {id: 0, name: '--'}, 
      {id: 1, name: 'スタジアム受け取り可'}, 
      {id: 2, name: '宅配（着払い）のみ可'},
    ]
      include ActiveHash::Associations
      has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_one :order

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :delivery

  with_options presence: true do
    validates :image
    validates :name
    validates :info
    validates :price,    numericality: { with: /\A[0-9]+\z/, message: 'Half-width number' }
    validates :price_discrimination,    numericality: { with: /\A[0-9]+\z/, message: 'Half-width number' }
    end

  with_options numericality: { other_than: 0, message: 'Select'  } do
      validates :category_id 
      validates :delivery_id 
  end
end

app/models/member.rb
class Member < ActiveHash::Base
  self.data = [
    {id: 0, name: '--'}, 
    {id: 1, name: '年間チケット会員'}, 
    {id: 2, name: 'レギュラー会員'},
    {id: 3, name: '非会員'}
]
include ActiveHash::Associations
  has_many :users
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :item
  has_one    :address
end

app/models/order_donation.rb
class OrderDonation
  include ActiveModel::Model
  attr_accessor :user_id, :item_id, :postal_code, :prefecture_id, :city, :address, :building, :phone_number

  with_options presence: true do
    validates :postal_code, format: { with: /\A[0-9]{3}-[0-9]{4}\z/, message: "input correctly" }
    validates :city
    validates :address
    validates :user_id
    validates :item_id
    end
  
    validates :prefecture_id, numericality: { other_than: 0, message: "Select" }
    validates :phone_number,  presence: true, numericality: { with: /\A[0-9]+\z/, message: "is Half-width number" }
    validates :phone_number, format: { with: /\A[0-9]{,11}\z/, message: "is less than 11 number characters" }
  
    def save
      order = Order.create(user_id: user_id, item_id: item_id)
      Address.create(postal_code: postal_code, prefecture_id: prefecture_id, city: city, address: address, building: building, phone_number: phone_number, order_id: order.id)
    end
  end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    {id: 0, name: '--'}, {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, 
    {id: 3, name: '岩手県'}, {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, 
    {id: 6, name: '山形県'}, {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, 
    {id: 9, name: '栃木県'}, {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, 
    {id: 12, name: '千葉県'}, {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, 
    {id: 15, name: '新潟県'}, {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, 
    {id: 18, name: '福井県'}, {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, 
    {id: 21, name: '岐阜県'}, {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, 
    {id: 24, name: '三重県'}, {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, 
    {id: 27, name: '大阪府'}, {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, 
    {id: 30, name: '和歌山県'}, {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, 
    {id: 33, name: '岡山県'}, {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, 
    {id: 36, name: '徳島県'}, {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, 
    {id: 39, name: '高知県'}, {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, 
    {id: 42, name: '長崎県'}, {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, 
    {id: 45, name: '宮崎県'}, {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
]

  include ActiveHash::Associations
  has_many :items
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  has_many :service_orders

  validates :content,    presence: true
  validates :limit_day,  presence: true, format: { with: /\A\d{4}-\d{2}-\d{2}\z/, message: "input correctly" }
  validates :target,     presence: true
  validates :release_day,  presence: true, format: { with: /\A\d{4}-\d{2}-\d{2}\z/, message: "input correctly" }
end

app/models/service_order.rb
class ServiceOrder < ApplicationRecord
  belongs_to :user
  belongs_to :service
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :items
         has_many :orders
         has_many :comments
         has_many :services
         has_many :service_orders
         enum admin: {normal: 0, staff:1}

         extend ActiveHash::Associations::ActiveRecordExtensions
         belongs_to_active_hash :member

         validates :email,  presence: true
         validates :password,  presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message: 'Include both letters and numbers' }
         validates :name,  presence: true, format: { with: /\A[ぁ-んァ-ヶー-龥々]+\z/, message: 'Full-width characters' }
         validates :name_kana,  presence: true, format: { with: /\A[ァ-ヶー]+\z/, message: 'Full-width katakana characters' } 
         validates :member_id,  numericality: { other_than: 0, message: 'Select'  }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!,  only: [:show, :edit]

  def show
    if params[:id].to_i == current_user.id
      @user = User.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to  user_path(@user.id)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :name_kana, :email, :password, :member_id, :admin)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/allappoints_helper.rb
module AllappointsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_with model: @user, url: user_path(current_user.id), class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      会員情報入力
    </h1>
    <div class = "user-edit">
      <%=link_to '戻る', user_path(current_user.id) %>
    </div>
  </div>


  <%= render 'shared/error_messages', model: f.object %>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :name, class:"input-name", id:"name", placeholder:"例) 山田太郎" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前カナ(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :name_kana, class:"input-name", id:"name-kana", placeholder:"例) ヤマダタロウ" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password, class:"input-default", id:"password", placeholder:"6文字以上の半角英数字" %>
    <p class='info-text'>※英字と数字の両方を含めて設定してください</p>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード(確認)</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password_confirmation, class:"input-default", id:"password-confirmation", placeholder:"同じパスワードを入力して下さい" %>
  </div>
  <div class="form-group">
    <div class='form-info-header'>
      会員の種類
    </div>
    <p class='form-info-text'>
      <%= f.collection_select(:member_id, Member.all, :id, :name, {}, {class:"select-box", id:"member"}) %>
    </p>
  </div>
  <div class='register-btn'>
    <%= f.submit "会員登録" ,class:"register-red-btn" %>
  </div>
  <br><div class = "attention">※変更後、再度ログインお願いします。</div>
</div>
<% end %>

app/views/users/show.html.erb
<header>
<div class= "main">
  <h1 class = "title">ユーザートップページ</h1>
</div>
<div class = "header-top">
<ul>
  <h3 class= "greeting">こんにちは<span class = "username"><%= @user.name %></span>さん</h3>
</ul>
<% if user_signed_in? %>
<ul class = "lists-right">
  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout1"  %>
</ul>
<% end %>
</div>
</header>
<body>
<div class = "body">
<% if @user.id == 1 %>
  <div class = "user">
    <%= link_to "登録ユーザー一覧",admin_index_path, model: :get  %>
  </div>
  <div class = "order">
    <%= link_to "注文一覧", admin_path(current_user.id), method: :get %>
  </div>
  <div class = "service1">
    <%= link_to "サービス応募者", service_lists_path, method: :get %>
  </div>
<% else%>
<div class = "buy">
 <%= link_to "購入履歴", purchase_path(@user.id), method: :get %>
 </div>
 <div class = "service1">
   <%= link_to 'ファンサービスに応募', services_path, method: :get %>
 </div>
  <div class = "service1">
    <%= link_to "応募したサービス一覧", allappoints_path, method: :get %>
  </div>
<% end %>
<div class = "item">
<%= link_to "商品ページ",root_path  %>
</div>
<div class = "change">
<%= link_to "登録情報変更",edit_user_path(@user.id), method: :get  %>
</div>
</div>

<div>
 <h1 class = "information">登録情報</h1>
</div>
<table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item1">名前</th>
          <td class="detail-value1"><%= @user.name %></td>
        </tr>
        <tr>
          <th class="detail-item2">メールアドレス</th>
          <td class="detail-value2"><%= @user.email %></td>
        </tr>
        <tr>
          <th class="detail-item3">会員の種類</th>
          <td class="detail-value3"><%= @user.member.name %></td>
        </tr>
      </tbody>
    </table>
  </div>
</body>