config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "items#index"
  resources :items do
    get 'items/search'
    resources :orders, only: [:index, :create]
  end
  resources :users, only: [:show, :edit, :update]
  resources :admin, only: [:index, :show]
  resources :purchases, only: :show
  resources :comments, only: [:index, :new, :show, :create]
  resources :services do
  resources :service_orders, only: [:index, :new, :create]
  end
  resources :allappoints, only: [:index]
  resources :service_lists, only: [:index]
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :order
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    {id: 0, name: '--'}, 
    {id: 1, name: 'ユニフォーム'}, 
    {id: 2, name: 'トレーニングウェア'}, 
    {id: 3, name: 'プレーヤーグッズ'}, 
    {id: 4, name: 'タオル'}, 
    {id: 5, name: '応援グッズ'}, 
    {id: 6, name: 'アパレル'}, 
    {id: 7, name: 'ステーショナリー'}, 
    {id: 8, name: 'バッグ'}, 
    {id: 9, name: 'その他'}, 
]

  include ActiveHash::Associations
  has_many :items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user

  validates :message,     presence: true
end

app/models/delivery.rb
class Delivery < ActiveHash::Base
    self.data = [
      {id: 0, name: '--'}, 
      {id: 1, name: 'スタジアム受け取り可'}, 
      {id: 2, name: '宅配（着払い）のみ可'},
    ]
      include ActiveHash::Associations
      has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_one :order

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :delivery

  with_options presence: true do
    validates :image
    validates :name
    validates :info
    validates :price,    numericality: { with: /\A[0-9]+\z/, message: 'Half-width number' }
    validates :price_discrimination,    numericality: { with: /\A[0-9]+\z/, message: 'Half-width number' }
    end

  with_options numericality: { other_than: 0, message: 'Select'  } do
      validates :category_id 
      validates :delivery_id 
  end
end

app/models/member.rb
class Member < ActiveHash::Base
  self.data = [
    {id: 0, name: '--'}, 
    {id: 1, name: '年間チケット会員'}, 
    {id: 2, name: 'レギュラー会員'},
    {id: 3, name: '非会員'}
]
include ActiveHash::Associations
  has_many :users
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :item
  has_one    :address
end

app/models/order_donation.rb
class OrderDonation
  include ActiveModel::Model
  attr_accessor :user_id, :item_id, :postal_code, :prefecture_id, :city, :address, :building, :phone_number

  with_options presence: true do
    validates :postal_code, format: { with: /\A[0-9]{3}-[0-9]{4}\z/, message: "input correctly" }
    validates :city
    validates :address
    validates :user_id
    validates :item_id
    end
  
    validates :prefecture_id, numericality: { other_than: 0, message: "Select" }
    validates :phone_number,  presence: true, numericality: { with: /\A[0-9]+\z/, message: "is Half-width number" }
    validates :phone_number, format: { with: /\A[0-9]{,11}\z/, message: "is less than 11 number characters" }
  
    def save
      order = Order.create(user_id: user_id, item_id: item_id)
      Address.create(postal_code: postal_code, prefecture_id: prefecture_id, city: city, address: address, building: building, phone_number: phone_number, order_id: order.id)
    end
  end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    {id: 0, name: '--'}, {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, 
    {id: 3, name: '岩手県'}, {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, 
    {id: 6, name: '山形県'}, {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, 
    {id: 9, name: '栃木県'}, {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, 
    {id: 12, name: '千葉県'}, {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, 
    {id: 15, name: '新潟県'}, {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, 
    {id: 18, name: '福井県'}, {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, 
    {id: 21, name: '岐阜県'}, {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, 
    {id: 24, name: '三重県'}, {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, 
    {id: 27, name: '大阪府'}, {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, 
    {id: 30, name: '和歌山県'}, {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, 
    {id: 33, name: '岡山県'}, {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, 
    {id: 36, name: '徳島県'}, {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, 
    {id: 39, name: '高知県'}, {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, 
    {id: 42, name: '長崎県'}, {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, 
    {id: 45, name: '宮崎県'}, {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
]

  include ActiveHash::Associations
  has_many :items
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  has_many :service_orders

  validates :content,    presence: true
  validates :limit_day,  presence: true, format: { with: /\A\d{4}-\d{2}-\d{2}\z/, message: "input correctly" }
  validates :target,     presence: true
  validates :release_day,  presence: true, format: { with: /\A\d{4}-\d{2}-\d{2}\z/, message: "input correctly" }
end

app/models/service_order.rb
class ServiceOrder < ApplicationRecord
  belongs_to :user
  belongs_to :service
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :items
         has_many :orders
         has_many :comments
         has_many :services
         has_many :service_orders
         enum admin: {normal: 0, staff:1}

         extend ActiveHash::Associations::ActiveRecordExtensions
         belongs_to_active_hash :member

         validates :email,  presence: true
         validates :password,  presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message: 'Include both letters and numbers' }
         validates :name,  presence: true, format: { with: /\A[ぁ-んァ-ヶー-龥々]+\z/, message: 'Full-width characters' }
         validates :name_kana,  presence: true, format: { with: /\A[ァ-ヶー]+\z/, message: 'Full-width katakana characters' } 
         validates :member_id,  numericality: { other_than: 0, message: 'Select'  }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!,  except: [:index, :show]
  before_action :set_item, only: [:edit, :update, :show, :destroy]
  before_action :move_to_index, only: :edit

  def index
    @items = Item.all
    @items = Item.page(params[:page]).per(20)
  end
  
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to  items_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to  items_path
    else
      render :edit
    end
  end

  def destroy
    if user_signed_in? && current_user.id == 1
      @item.destroy
      redirect_to  items_path
    else
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :info, :price, :category_id, :delivery_id, :image, :price_discrimination).merge(user_id: current_user.id)
  end

  def move_to_index
    unless current_user.id == 1
      redirect_to action: :index
    end
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/allappoints_helper.rb
module AllappointsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/edit.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model:  @item, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="weight-bold-text">
        商品イメージ
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>

    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品情報
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :info, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <div class="items-detail">
      <div class="weight-bold-text">カテゴリー</div>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
    </div>

    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>受渡方法について</span>
      </div>
        <%= f.collection_select(:delivery_id, Delivery.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
    </div>

    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格</span>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"半角数字で入力" %>
        </div>
        <div class="price-content">
          <span>会員価格</span>
          <span class="indispensable">必須</span>
          <span class="sell-yen">¥</span>
            <%= f.text_field :price_discrimination, class:"price-input", id:"item-price", placeholder:"半角数字で入力" %>          
        </div>
        </span>
      </div>
    </div>

    <p></p>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
</div>

app/views/items/index.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class='title-contents'>
    <h2 class='service-title'>
      ようこそ<br>横浜Fマリノスオンラインショップへ
    </h2>
    <% if user_signed_in? %>
    <% if current_user.id == 1 %>
    <%= link_to(new_item_path, class: 'purchase-btn') do %>
    <span class='purchase-btn-text'>出品</span>
    <% end %>
    <% end %>
    <% end %>
  </div>
  <div class = "space">
      <%= image_tag "IMG_0367.JPG", size: '150x200' %>
      <%= image_tag "IMG_0359.JPG", size: '400x200' %>
      <%= image_tag "IMG_0325.GIF", size: '150x200' %>
   </div>
   
  <div class='item-contents'>
    <div class = "item-arrange">
      <h2 class = "arrange">商品一覧</h2>
    </div>
    <h6 class = "attention">※スタジアム受取希望の場合、購入手続き後、3日以内に連絡下さい<h6>
    <br>
    <div class = "page">
       <%= paginate @items %>
    </div>
    <ul class='item-lists'>
      <% @items.each do |item| %>
      <li class='list'>
        <%= link_to item_path(item.id) do %>
        <div class='item-img-content'>
          <%= image_tag item.image, class: "item-img" %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span>一般価格：<%= item.price %>円</span>
            <span>会員価格：<%= item.price_discrimination %>円</span>
            <div class='star-btn'>
              <span class='star-count'><%= item.delivery.name %></span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
      <% unless @items.present? %>
      <li class='list'>
        <%= link_to '#' do %>
        <div class='item-info'>
          <h3 class='item-name'>
            現在、商品は完売しております。またのご利用をお待ちしております。
          </h3>
        </div>
        <% end %>
      </li>
      <% end %>
    </ul>
    <div class = "page">
       <%= paginate @items %>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model:  @item, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="weight-bold-text">
        商品イメージ
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>

    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品情報
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :info, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <div class="items-detail">
      <div class="weight-bold-text">カテゴリー</div>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
    </div>

    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>受渡方法について</span>
      </div>
        <%= f.collection_select(:delivery_id, Delivery.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
    </div>

    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格</span>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"半角数字で入力" %>
        </div>
        <div class="price-content">
          <span>会員価格</span>
          <span class="indispensable">必須</span>
          <span class="sell-yen">¥</span>
            <%= f.text_field :price_discrimination, class:"price-input", id:"item-price", placeholder:"半角数字で入力" %>          
        </div>
        </span>
      </div>
    </div>

    <p></p>
    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
</div>

app/views/items/show.html.erb
<%= render "shared/header" %>

<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.name %>
    </h2>
    <div class='item-img-content'>
      <%= image_tag @item.image ,class:"item-box-img" %>
    </div>
    <div class="item-price-box">
      <span class="item-price">
        一般価格：¥ <%= @item.price %>
        <br>会員価格：¥ <%= @item.price_discrimination %>
      </span>
      <span class="item-postage">
      </span>
    </div>

    <% if user_signed_in? %>
      <% if current_user.id == @item.user_id %>
      <%= link_to '商品の編集', edit_item_path(@item.id), method: :get, class: "item-red-btn" %>
      <p class='or-text'>or</p>
      <%= link_to '削除', item_path(@item.id), method: :delete, class:'item-destroy' %>
      <% else %>
          <%= link_to '購入画面に進む', item_orders_path(@item.id) ,class:"item-red-btn"%>
      <% end %>
    <% end %>

    <div class="item-explain-box">
      <span><%= @item.info %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @item.user.name %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @item.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">受渡方法</th>
          <td class="detail-value"><%= @item.delivery.name %></td>
        </tr>
      </tbody>
    </table>
  </div>
      <p>
      <h6 class = "attention">※スタジアム受取希望の場合、購入手続き後、3日以内に連絡下さい<h6>
      </p>
  <div class = "foot">
    <%= link_to '戻る', items_path, method: :get %>
  </div>
</div>